linters:
  enable-all: true
  disable:
    - dupl
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - lll
    - godox
    - wsl
    - gosec
    - whitespace
    - gocognit
  # Run with --fast=false for more extensive checks
  fast: true
issues:
  max-same-issues: 0
  max-issues-per-linter: 0
  # List of regexps of issue texts to exclude, empty list by default.
  exclude:
    - Using the variable on range scope `(tc)|(rt)|(tt)|(test)|(testcase)|(testCase)` in function literal
run:
  deadline: 4m
  skip-files:
    - "zz_generated.*\\.go$"
  skip-dirs:
    - third_party
