linters:
  enable-all: true
  disable:
    - dupl
    - errcheck
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocritic
    - lll
    - scopelint
    - staticcheck
    - unparam
    - unused
  # Run with --fast=false for more extensive checks
  fast: true
issue:
  max-same-issues: 0
  max-per-linter: 0
run:
  deadline: 2m
  skip-files:
    - "zz_generated.*\\.go$"
