linters:
  enable-all: true
  disable:
    - dupl
    - errcheck
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocritic
    - lll
    - scopelint
    - staticcheck
    - unparam
    - unused
  # Run with --fast=false for more extensive checks
  fast: true
issues:
  max-same-issues: 0
  max-issues-per-linter: 0
  exclude:
    - "G108: Profiling endpoint is automatically exposed on /debug/pprof"
run:
  deadline: 2m
  skip-files:
    - "zz_generated.*\\.go$"
  skip-dirs:
    - third_party
