linters:
  disable-all: true
  enable:
  - asciicheck
  - bodyclose
  - deadcode
  - depguard
  - dogsled
  - exportloopref
  - errcheck
  - goconst
  - gocritic
  - gocyclo
  - gofmt
  - goimports
  - golint
  - goprintffuncname
  - gosec
  - gosimple
  - govet
  - ineffassign
  - misspell
  - nakedret
  - nolintlint
  - prealloc
  - rowserrcheck
  - staticcheck
  - structcheck
  - stylecheck
  - typecheck
  - unconvert
  - unparam
  - varcheck
  - godot
  - whitespace

issues:
  max-same-issues: 0
  max-issues-per-linter: 0
  # We are disabling default golangci exclusions because we want to help reviewers to focus on reviewing the most relevant
  # changes in PRs and avoid nitpicking.
  exclude-use-default: false
  # List of regexps of issue texts to exclude, empty list by default.
  exclude:
  - "G108: Profiling endpoint is automatically exposed on /debug/pprof"
  - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv). is not checked
  - exported method `.*.(Reconcile|SetupWithManager|SetupWebhookWithManager)` should have comment or be unexported
  # The following are being worked on to remove their exclusion. This list should be reduced or go away all together over time.
  # If it is decided they will not be addressed they should be moved above this comment.
  - Subprocess launch(ed with variable|ing should be audited)
  - (Expect directory permissions to be 0750 or less|Expect file permissions to be 0600 or less)
  - (G104|G307)
  exclude-rules:
  # With Go 1.16, the new embed directive can be used with an un-named import,
  # golint only allows these to be imported in a main.go, which wouldn't work for us.
  # This directive allows the embed package to be imported with an underscore everywhere.
  - linters:
    - golint
    source: _ "embed"
  # Exclude some packages or code to require comments, for example test code, or fake clients.
  - linters:
    - golint
    text: exported (method|function|type|const) (.+) should have comment or be unexported
    source: (func|type).*Fake.*
  - linters:
    - golint
    text: exported (method|function|type|const) (.+) should have comment or be unexported
    path: fake_\.go
  - linters:
    - golint
    text: exported (method|function|type|const) (.+) should have comment or be unexported
    path: .*test/(providers|framework|e2e).*.go
  # Disable unparam "always receives" which might not be really
  # useful when building libraries.
  - linters:
    - unparam
    text: always receives
  # Dot imports for gomega or ginkgo are allowed
  # within test files.
  - path: _test\.go
    text: should not use dot imports
  - path: _test\.go
    text: cyclomatic complexity
  - path: test/(framework|e2e).*.go
    text: should not use dot imports

run:
  timeout: 10m
  skip-files:
  - "zz_generated.*\\.go$"
  - ".*conversion.*\\.go$"
  skip-dirs:
  - third_party
  allow-parallel-runners: true
