# Netlify build instructions
[build]
    command = "./docs/book/install-and-build.sh"
    publish = "docs/book/book"

# Standard Netlify redirects
[[redirects]]
    from = "https://master--kubernetes-sigs-cluster-api.netlify.com/*"
    to = "https://dev.cluster-api.sigs.k8s.io/:splat"
    status = 301
    force = true

# HTTP-to-HTTPS rules
[[redirects]]
    from = "http://dev.cluster-api.sigs.k8s.io/*"
    to = "https://dev.cluster-api.sigs.k8s.io/:splat"
    status = 301
    force = true

[[redirects]]
    from = "http://master--kubernetes-sigs-cluster-api.netlify.com/*"
    to = "http://dev.cluster-api.sigs.k8s.io/:splat"
    status = 301
    force = true
