resources:
  - namespace.yaml

helmCharts:
  - name: promtail
    repo: https://grafana.github.io/helm-charts
    releaseName: promtail
    namespace: observability
    valuesFile: ./promtail/values.yaml
  - name: loki
    repo: https://grafana.github.io/helm-charts
    releaseName: loki
    namespace: observability
    valuesFile: ./loki/values.yaml
  - name: grafana
    repo: https://grafana.github.io/helm-charts
    releaseName: grafana
    namespace: observability
    valuesFile: ./grafana/values.yaml
